### ISSUE TITLE
Not working on aspire E5-475G-544J 

### ISSUE THREAD

**Issue by David0601d** [frederik-h/acer-wmi-battery#15]
$ sudo dmesg
[    3.625291] acer_battery_wmi: loading out-of-tree module taints kernel.
[    3.625318] acer_battery_wmi: module verification failed: signature and/or required key missing - tainting kernel
I got this errors, But still don't know how to deal with

**Comment by frederik-h** [comment]
This problem is not specific to this module, i.e. I suppose you would have similar problems with any out-of-tree module. You would probably have to figure out how to sign the module or disable the signature checking on your system somehow.
