### ISSUE TITLE
Works great for Acer Nitro 5 AN515-55 2021

### ISSUE THREAD

**Issue by macvenez** [frederik-h/acer-wmi-battery#16]
Hi, thank you for that amazing work.
I just wanted to confirm that it works on Acer Nitro 5 AN515-55 2021.
Specs are:
CPU: i5-10300H
GPU: GTX 1650 Ti Mobile 4GB
OS: Ubuntu 22.04.1 LTS

**Comment by frederik-h** [comment]
Thanks for your feedback!
