### ISSUE TITLE
Difference from another repo?

### ISSUE THREAD

**Issue by Brli** [frederik-h/acer-wmi-battery#2]
namely, this one: https://github.com/maxco2/acer-battery-wmi

**Comment by frederik-h** [comment]
I was not aware of this repository when I implemented my driver.   
This driver seems to implement essentially the same functionality for enabling the battery health mode, but I don't see an option to enable the battery calibration.

**Comment by agusti30** [comment]
I got this warning, sorry I don't know how to switch gcc version or install multiple gcc version in Fedora. Try to look it up in Internet still didn't work. 

warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 15.0.1 20250418 (Red Hat 15.0.1-0)
  You are using:           gcc (GCC) 15.0.1 20250329 (Red Hat 15.0.1-0)

**Comment by Anonymous941** [comment]
@agusti30 You can switch to that exact version of GCC, or just ignore the warning (it's probably not going to cause problems)
