### ISSUE TITLE
How to check good functioning

### ISSUE THREAD

**Issue by Friptick** [frederik-h/acer-wmi-battery#29]
Quick support request!

After the machine has been plugged in for a while, and with the following outputs unchanging, can I assume that the module is working properly and that the battery charge has been limited to 80%?

```
$ cat /sys/bus/wmi/drivers/acer-wmi-battery/health_mode
1
$ cat /sys/class/power_supply/BAT0/capacity
79
$ cat /sys/class/power_supply/BAT0/status
Not charging
```

**Comment by frederik-h** [comment]
Looks right!

**Comment by Friptick** [comment]
PS Great. Take this as confirmation that your module works with model SF-114. Thanks again for your work.
