### ISSUE TITLE
Working on Acer Swift X 2022 (SFX14-51G)

### ISSUE THREAD

**Issue by Diman119** [frederik-h/acer-wmi-battery#32]
With health mode enabled the battery does not exceed 79%. If it already was at above 79% when health mode was enabled, the battery does not charge or discharge, the laptop runs entirely on AC. With health mode off charging happens as expected. Switching the modes takes effect after a few seconds even without reconnecting the charger.
Have not tested calibration mode.

**Comment by Diman119** [comment]
Also you may want to update the README with all new working models :)

**Comment by frederik-h** [comment]
> Also you may want to update the README with all new working models :)

Thanks for the feedback about your laptop. I would also take a PR :-).
