### ISSUE TITLE
Skipping BTF Generation due to unavaliablity of vmlinux 

### ISSUE THREAD

**Issue by erhangk** [frederik-h/acer-wmi-battery#33]
I got the error below while building the repo on Fedora 38.

``
[erhangk@fedora acer-wmi-battery]$ make
make -C /lib/modules/6.4.14-200.fc38.x86_64/build M=/home/erhangk/acer-wmi-battery modules
make[1]: Entering directory '/usr/src/kernels/6.4.14-200.fc38.x86_64'
  CC [M]  /home/erhangk/acer-wmi-battery/acer-wmi-battery.o
  MODPOST /home/erhangk/acer-wmi-battery/Module.symvers
  CC [M]  /home/erhangk/acer-wmi-battery/acer-wmi-battery.mod.o
  LD [M]  /home/erhangk/acer-wmi-battery/acer-wmi-battery.ko
  BTF [M] /home/erhangk/acer-wmi-battery/acer-wmi-battery.ko
Skipping BTF generation for /home/erhangk/acer-wmi-battery/acer-wmi-battery.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/kernels/6.4.14-200.fc38.x86_64'
``

When i try to turn on health mode sometimes it just works and enable it but sometimes i get this error:

``
tee: /sys/bus/wmi/drivers/acer-wmi-battery/health_mode: No such file or directory
``

I don't know if it is because of Fedora or vmlinux, is there any fix about this?

**Comment by mochechan** [comment]
Just do the following commands before making if you are using ubuntu linux.
`
sudo apt -y install dwarves
sudo cp -avi /sys/kernel/btf/vmlinux /usr/lib/modules/`uname -r`/build/
`
