### ISSUE TITLE
Working on Swift Go 14 SFG14-71

### ISSUE THREAD

**Issue by TID41** [frederik-h/acer-wmi-battery#35]
Driver works as intended with the SFG14-71. I am using it in KDE Neon with KDE's Plasma desktop, using the plasmoid (widget) entitled "Acer Battery Limit Switcher." The plasmoid and driver work very well to provide the battery saver (stop at 80%) and calibrate mode functionality.

**Comment by frederik-h** [comment]
Thanks for the feedback!
