### ISSUE TITLE
Working on Acer Nitro AN515-57

### ISSUE THREAD

**Issue by brenobaptista** [frederik-h/acer-wmi-battery#38]
Please review #31

**Comment by brenobaptista** [comment]
It fixed for a lot longer but after updating to new kernel a day later it stopped working again. I had to run `make` in the project again then I was able to use it.

![image](https://github.com/frederik-h/acer-wmi-battery/assets/47641641/86941025-478d-4911-af5e-2f6f107204ed)

**Comment by frederik-h** [comment]
Thanks for the feedback. I'll take a look at the updated PR.
