### ISSUE TITLE
Feedback for Acer Enduro N3 Urban (EUN314A-51W)

### ISSUE THREAD

**Issue by jacobcalvert** [frederik-h/acer-wmi-battery#4]
# Summary
The kernel mod works, but I'd like to detail all the behaviors I'm seeing for completeness. 

# System Software
- Linux Mint 21 Cinnamon
- Kernel v5.15.0-43-generic

# Behaviors
- `echo 1 > /sys/bus/wmi/drivers/acer-wmi-battery/health_mode` works to change the battery charging behavior
- Battery does discharge on wall power while above 80% charge
- Battery remaining estimate jumps around constantly on wall power while charge above 80%
  - Remaining estimate settles down when off wall power while charge above 80%
- Battery remains charged at XX% on wall power
- `cat /sys/bus/wmi/drivers/acer-wmi-battery/health_mode` always returns `0`
- `cat bus/acpi/drivers/battery/PNP0C0A\:00/power_supply/BAT1/status` changes from `Discharging` to `Charging` at 80% level
- With Health Mode "enabled" the battery will not exceed 79% if it has fallen below 80%. 
- `echo 0 > /sys/bus/wmi/drivers/acer-wmi-battery/health_mode` works to change the battery back to "normal" charging behavior

**Comment by frederik-h** [comment]
Thanks for the detailed feedback!
