### ISSUE TITLE
idk why am I getting this error... any solution?

### ISSUE THREAD

**Issue by Cortex0715** [frederik-h/acer-wmi-battery#48]
cortex@cortex-Aspire-A715-42G:~/acer-wmi-battery$ sudo insmod acer-wmi-battery.ko
insmod: ERROR: could not insert module acer-wmi-battery.ko: Operation not permitted

**Comment by MestoloPomello** [comment]
Do you have Secure Boot active? If you have and can't turn it off, you can try signing the module with a X.509 certificate and re-run the command. I did it some time ago by following the top answer [here](https://unix.stackexchange.com/questions/751517/insmod-causes-key-rejected-by-service), i don't know if there is a more straightforward way to do it

**Comment by frederik-h** [comment]
Closing because this does not look like a problem that is specific to this module.

**Comment by ghost** [comment]
Can confirm, this does allow the insmod proceed.

> Do you have Secure Boot active? If you have and can't turn it off, you can try signing the module with a X.509 certificate and re-run the command. I did it some time ago by following the top answer [here](https://unix.stackexchange.com/questions/751517/insmod-causes-key-rejected-by-service), i don't know if there is a more straightforward way to do it
