### ISSUE TITLE
Should report when the battery isn't charging anymore

### ISSUE THREAD

**Issue by wojpawlik** [frederik-h/acer-wmi-battery#5]

**Comment by frederik-h** [comment]
You are right that this driver does not produce a proper message for this event. But the acer-wmi driver actually catches the event but does not know how to handle it. This produces the message "acer_wmi: Unknown function number - 8 - 0" or  "acer_wmi: Unknown function number - 8 - 1" when charging stops or is resumed. The event code 11 is used for indicating the beginning and the end of  battery calibration.
If we want proper handling for those messages, I think it must be added to the acer-wmi driver. The functionality of the acer-wmi-battery driver should probably also be added there.

**Comment by wojpawlik** [comment]
Works on kernel 5.19.11.
