### ISSUE TITLE
Made an AUR Package of the DKMS Variant for Arch Linux

### ISSUE THREAD

**Issue by ryanbarillos** [frederik-h/acer-wmi-battery#52]
Hi. 

I'd like to let you know that I've made an AUR package of the DKMS variant of this kernel for Arch Linux, and I can say it's working 100% on my system and on my laptop. Hopefully this will get more exposure on the other side of Linux.

Link to AUR package: [here](https://aur.archlinux.org/packages/acer-wmi-battery-dkms-git)
When I have the time again, I'll also work toward uploading the main variant to the AUR as well.

**Comment by frederik-h** [comment]
Great!

**Comment by ryanbarillos** [comment]
Done! There are now two ways to install this driver for Arch Linux: 

- [acer-wmi-battery-dkms](https://aur.archlinux.org/packages/acer-wmi-battery-dkms) (To get latest package release)
- [acer-wmi-battery-dkms-git](https://aur.archlinux.org/packages/acer-wmi-battery-dkms-got) (To get latest GitHub commit)
