### ISSUE TITLE
Feedback for Acer Helios 300 (PH315-54)

### ISSUE THREAD

**Issue by nickuc** [frederik-h/acer-wmi-battery#8]
# Summary
The Kernel module works perfectly, with the same behavior as Care Center on Windows.

# System Software
* Pop!_OS 22.04 LTS x86-64
* Kernel v6.0.2-76060002-generic

**Comment by frederik-h** [comment]
Thank you for the feedback!

**Comment by aorizondo** [comment]
Confirmed working on Predator Helios PH315-53 as well, great job!
